export const blades: Blade[] = [
  {
    Blade_Name: "Butterfly Viscaria",
    Blade_Brand: "Butterfly",
    Blade_Speed: 92,
    Blade_Spin: 88,
    Blade_Control: 75,
    Blade_Power: 92,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 78,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "The gold standard for modern offensive play. Viscaria's Koto outer ply and ALC fiber provide the crisp, powerful, and consistent benchmark used by countless professionals.",
  },
  {
    Blade_Name: "Butterfly Timo Boll ALC",
    Blade_Brand: "Butterfly",
    Blade_Speed: 93,
    Blade_Spin: 87,
    Blade_Control: 74,
    Blade_Power: 93,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 80,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Based on the Viscaria construction but with a slightly sharper, stiffer feel. It is optimized for close-to-the-table counter-looping and precise, powerful attacks.",
  },
  {
    Blade_Name: "DHS Hurricane Long 5",
    Blade_Brand: "DHS",
    Blade_Speed: 95,
    Blade_Spin: 89,
    Blade_Control: 76,
    Blade_Power: 95,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The ultimate \"Innerforce\" ALC blade. Limba outer plies over a carbon core offer massive dwell time and safety for slow loops, unlocking devastating power on full-force strokes.",
  },
  {
    Blade_Name: "Stiga Clipper Wood",
    Blade_Brand: "Stiga",
    Blade_Speed: 86,
    Blade_Spin: 95,
    Blade_Control: 82,
    Blade_Power: 86,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 75,
    Blade_Material: "All-Wood",
    Blade_Description: "The legendary all-wood powerhouse. Known for its thick composition and solid feel, it provides incredible control for blocking and driving, making it the perfect choice for traditional power players.",
  },
  {
    Blade_Name: "Nittaku Acoustic",
    Blade_Brand: "Nittaku",
    Blade_Speed: 78,
    Blade_Spin: 99,
    Blade_Control: 90,
    Blade_Power: 78,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "All-Wood",
    Blade_Description: "Built using acoustic instrument manufacturing techniques. The special gluing process gives it unique \"feedback\" and flexibility, offering unparalleled control and spin for technical, loop-focused players.",
  },
  {
    Blade_Name: "Butterfly Innerforce Layer ALC",
    Blade_Brand: "Butterfly",
    Blade_Speed: 89,
    Blade_Spin: 93,
    Blade_Control: 80,
    Blade_Power: 89,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 68,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "Butterfly's answer to the Inner-carbon demand. This blade acts like a controllable 5-ply wood on soft contact but activates the ALC core for powerful, safe looping on strong attacks.",
  },
  {
    Blade_Name: "Stiga Carbonado 145",
    Blade_Brand: "Stiga",
    Blade_Speed: 94,
    Blade_Spin: 85,
    Blade_Control: 72,
    Blade_Power: 94,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 85,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A high-tech beast using unique TeXtreme flat-weave carbon. The 145 angle provides a wider sweet spot and a flatter, more direct trajectory for aggressive smashers and drivers.",
  },
  {
    Blade_Name: "Xiom Stradivarius",
    Blade_Brand: "Xiom",
    Blade_Speed: 91,
    Blade_Spin: 89,
    Blade_Control: 76,
    Blade_Power: 91,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 76,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A high-value alternative to the Viscaria class. The Aramid Carbon (a slightly softer ALC variant) over Koto provides a crisp, responsive feel for dynamic all-round offensive play.",
  },
  {
    Blade_Name: "Butterfly Primorac Carbon",
    Blade_Brand: "Butterfly",
    Blade_Speed: 98,
    Blade_Spin: 73,
    Blade_Control: 60,
    Blade_Power: 98,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 95,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A pure speed legend. Thick Cypress outer plies combined with T5000 carbon make this one of the stiffest and fastest blades ever made, perfect for flat hitters and blockers.",
  },
  {
    Blade_Name: "Donier Balsa 14.5",
    Blade_Brand: "Donier",
    Blade_Speed: 84,
    Blade_Spin: 98,
    Blade_Control: 85,
    Blade_Power: 84,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The lightweight touch specialist. A thick Balsa core offers a unique low-gear control for short-game precision, while the fiberglass layers give surprising power on put-away shots.",
  },
  {
    Blade_Name: "Nittaku Violin",
    Blade_Brand: "Nittaku",
    Blade_Speed: 75,
    Blade_Spin: 99,
    Blade_Control: 94,
    Blade_Power: 75,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 55,
    Blade_Material: "All-Wood",
    Blade_Description: "The ultimate control blade. White Ash outer plies and special instrument gluing give the highest dwell time among all-wood blades, making it the spin-master's dream.",
  },
  {
    Blade_Name: "Butterfly Mazunov",
    Blade_Brand: "Butterfly",
    Blade_Speed: 88,
    Blade_Spin: 91,
    Blade_Control: 78,
    Blade_Power: 88,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 82,
    Blade_Material: "All-Wood",
    Blade_Description: "An anomaly\u2014a heavy, stiff, 5-ply wood that rivals many carbon blades in speed. Its unique Planchonello outer plies create a massive \"catapult effect\" for traditional, mid-distance power loops.",
  },
  {
    Blade_Name: "Stiga Infinity VPS V",
    Blade_Brand: "Stiga",
    Blade_Speed: 83,
    Blade_Spin: 99,
    Blade_Control: 86,
    Blade_Power: 83,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 65,
    Blade_Material: "All-Wood",
    Blade_Description: "Custom-treated \"Diamond Touch\" Limba plies. This VPS technology hardens the outer surface, giving the control of a 5-ply wood with a crispness that supports the modern, poly-ball loop game.",
  },
  {
    Blade_Name: "Joola Rossi Emotion",
    Blade_Brand: "Joola",
    Blade_Speed: 87,
    Blade_Spin: 97,
    Blade_Control: 84,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 62,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "A hidden gem in the Inner-carbon category. Its extremely soft Hinoki outer plies provide luxurious touch, while the inner carbon layers give strong, dynamic speed when needed.",
  },
  {
    Blade_Name: "Butterfly Timo Boll ZLC",
    Blade_Brand: "Butterfly",
    Blade_Speed: 96,
    Blade_Spin: 81,
    Blade_Control: 68,
    Blade_Power: 96,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 90,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Zylon/Carbon weave is lighter, stiffer, and more explosive than ALC. This blade offers massive speed and a direct, flat trajectory, rewarding advanced players with precise timing.",
  },
  {
    Blade_Name: "DHS Hurricane Long 3",
    Blade_Brand: "DHS",
    Blade_Speed: 87,
    Blade_Spin: 94,
    Blade_Control: 81,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 72,
    Blade_Material: "All-Wood",
    Blade_Description: "A refined, slightly softer version of the classic Stiga Clipper Wood. This 7-ply all-wood construction offers a perfect balance of control, solid feel, and traditional loop power.",
  },
  {
    Blade_Name: "Nittaku Tenaly Acoustic",
    Blade_Brand: "Nittaku",
    Blade_Speed: 78,
    Blade_Spin: 99,
    Blade_Control: 90,
    Blade_Power: 78,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "All-Wood",
    Blade_Description: "The ultimate ergonomic tool. It uses the award-winning Acoustic construction but with a patented curved handle that automatically aligns the blade angle for a natural, stress-free grip.",
  },
  {
    Blade_Name: "Butterfly Petr Korbel",
    Blade_Brand: "Butterfly",
    Blade_Speed: 76,
    Blade_Spin: 99,
    Blade_Control: 91,
    Blade_Power: 76,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 58,
    Blade_Material: "All-Wood",
    Blade_Description: "The benchmark 5-ply Limba looping blade. Thousands of players have developed their game with this blade, which excels at producing massive spin and consistent rallies.",
  },
  {
    Blade_Name: "Stiga Rosewood NCT V",
    Blade_Brand: "Stiga",
    Blade_Speed: 89,
    Blade_Spin: 90,
    Blade_Control: 77,
    Blade_Power: 89,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 85,
    Blade_Material: "All-Wood",
    Blade_Description: "Stiga's fastest all-wood blade. Extremely hard Rosewood outer plies combined with NCT technology make this blade stiff and responsive, supporting aggressive driving and smashing.",
  },
  {
    Blade_Name: "Victas Koki Niwa Wood",
    Blade_Brand: "Victas",
    Blade_Speed: 90,
    Blade_Spin: 88,
    Blade_Control: 75,
    Blade_Power: 90,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 80,
    Blade_Material: "All-Wood",
    Blade_Description: "Designed for the counter-attack specialist. This unique 7-ply construction uses softer outer plies over a hard core, giving the solid feel needed to absorb and redirect opponent power.",
  },
  {
    Blade_Name: "Butterfly Mizutani Jun ZLC",
    Blade_Brand: "Butterfly",
    Blade_Speed: 95,
    Blade_Spin: 83,
    Blade_Control: 70,
    Blade_Power: 95,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 88,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A direct competitor to the TB ZLC. It utilizes the same explosive ZLC material but is configured for a slightly higher throw angle, making it deadlier for high-speed, mid-distance looping rallies.",
  },
  {
    Blade_Name: "DHS Power G7",
    Blade_Brand: "DHS",
    Blade_Speed: 85,
    Blade_Spin: 96,
    Blade_Control: 83,
    Blade_Power: 85,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "All-Wood",
    Blade_Description: "A legendary high-value 7-ply wood. It offers a versatile, \"classic\" 7-ply feel, giving strong power for drives and blocks without sacrificing the dwell time needed for strong loops.",
  },
  {
    Blade_Name: "Donic Ovtcharov True Carbon",
    Blade_Brand: "Donic",
    Blade_Speed: 92,
    Blade_Spin: 87,
    Blade_Control: 74,
    Blade_Power: 92,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 79,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A direct, high-quality alternative to the Viscaria and TB ALC. Donic uses the identical Koto-ALC construction method, offering the same iconic crisp, versatile, professional offensive power.",
  },
  {
    Blade_Name: "Butterfly Gergely",
    Blade_Brand: "Butterfly",
    Blade_Speed: 97,
    Blade_Spin: 75,
    Blade_Control: 62,
    Blade_Power: 97,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 93,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A speed beast derived from the Primorac Carbon but with a larger, more traditional handle shape. Its T5000/Cypress build is optimized for flat hitting, smashing, and uncompromising offensive pressure.",
  },
  {
    Blade_Name: "Stiga Ebenholz NCT V",
    Blade_Brand: "Stiga",
    Blade_Speed: 91,
    Blade_Spin: 88,
    Blade_Control: 75,
    Blade_Power: 91,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 88,
    Blade_Material: "All-Wood",
    Blade_Description: "Stiga's fastest and stiffest all-wood blade, using extremely hard Ebony outer plies. This creates a massive \"rebound effect,\" perfect for players who demand maximum speed and a direct, powerful trajectory.",
  },
  {
    Blade_Name: "Nittaku Ludeack Power",
    Blade_Brand: "Nittaku",
    Blade_Speed: 88,
    Blade_Spin: 92,
    Blade_Control: 79,
    Blade_Power: 88,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 78,
    Blade_Material: "All-Wood",
    Blade_Description: "A refined, stiffer version of the Nittaku Ludeack. This 7-ply wood is built for the post-poly ball era, giving the extra speed needed for power drives and consistent, strong counter-looping.",
  },
  {
    Blade_Name: "Butterfly Innerforce Layer ZLC",
    Blade_Brand: "Butterfly",
    Blade_Speed: 93,
    Blade_Spin: 88,
    Blade_Control: 75,
    Blade_Power: 93,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 75,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The ultimate Inner-fiber blend. It features the soft feel and dwell time of a 5-ply wood on soft contact, but activating the powerful, stiff ZLC core unlocks massive, dynamic power on strong loops.",
  },
  {
    Blade_Name: "DHS Hurricane Hao III",
    Blade_Brand: "DHS",
    Blade_Speed: 89,
    Blade_Spin: 93,
    Blade_Control: 80,
    Blade_Power: 89,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 65,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "A unique \"glass-carbon\" mono-core blade. Its thick central carbon layer is designed specifically for the Penhold RPB grip, giving immense power for loop-drives while maintaining incredible touch.",
  },
  {
    Blade_Name: "Joola Aruna Off",
    Blade_Brand: "Joola",
    Blade_Speed: 89,
    Blade_Spin: 95,
    Blade_Control: 82,
    Blade_Power: 89,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 66,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "A classic Inner-carbon blade. Limba outer plies over a soft carbon core offer massive dwell time and safety for loops, while the inner carbon core provides linear, dynamic power on command.",
  },
  {
    Blade_Name: "Butterfly Timo Boll Spirit",
    Blade_Brand: "Butterfly",
    Blade_Speed: 91,
    Blade_Spin: 89,
    Blade_Control: 76,
    Blade_Power: 91,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 75,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "The predecessor to the TB ALC and a legend in its own right. This blade uses the exact Koto-ALC construction that set the benchmark for versatile, controlled-looping offensive power.",
  },
  {
    Blade_Name: "Andro Treiber Z",
    Blade_Brand: "Andro",
    Blade_Speed: 93,
    Blade_Spin: 91,
    Blade_Control: 78,
    Blade_Power: 93,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 82,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A rare multi-talent. The outer Z-fiber provides a massive sweet spot and a \"crispy\" feel that excels at both aggressive counter-loops and solid, constant blocks.",
  },
  {
    Blade_Name: "Gewo Aruna Carbon 2",
    Blade_Brand: "Gewo",
    Blade_Speed: 94,
    Blade_Spin: 86,
    Blade_Control: 73,
    Blade_Power: 94,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 84,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Built for the explosive style of Quadri Aruna. This blade uses high-energy carbon layers to maximize ball acceleration, making it a weapon for players who dominate with raw power.",
  },
  {
    Blade_Name: "Victas Koki Niwa ZC",
    Blade_Brand: "Victas",
    Blade_Speed: 96,
    Blade_Spin: 85,
    Blade_Control: 72,
    Blade_Power: 96,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 88,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A high-speed masterpiece. The Z-Carbon placement offers extreme stability and a direct trajectory, specifically designed for Koki Niwa's signature close-to-the-table \"artistic\" counters.",
  },
  {
    Blade_Name: "Donic Ovtcharov Senso V1",
    Blade_Brand: "Donic",
    Blade_Speed: 89,
    Blade_Spin: 91,
    Blade_Control: 78,
    Blade_Power: 89,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 80,
    Blade_Material: "All-Wood",
    Blade_Description: "A walnut-outer 7-ply beast. Donic\u2019s Senso technology (hollow handle) shifts the balance toward the head, providing unbelievable power for smashes while maintaining wood-like feedback.",
  },
  {
    Blade_Name: "Yasaka Rakza 7 Carbon",
    Blade_Brand: "Yasaka",
    Blade_Speed: 88,
    Blade_Spin: 97,
    Blade_Control: 84,
    Blade_Power: 88,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 65,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The ultimate synergy blade. By placing carbon on the core, Yasaka created a blade that behaves like a 5-ply wood on touch shots but provides a carbon \"kick\" during high-impact loops.",
  },
  {
    Blade_Name: "Andro Gauzy HL5",
    Blade_Brand: "Andro",
    Blade_Speed: 91,
    Blade_Spin: 92,
    Blade_Control: 79,
    Blade_Power: 91,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 74,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Designed by Simon Gauzy. It prioritizes creativity and feeling over \"brute\" speed. The KVL carbon stabilizes the blade, reducing vibration without killing the natural dwell time of the wood.",
  },
  {
    Blade_Name: "Gewo Force ARC Off",
    Blade_Brand: "Gewo",
    Blade_Speed: 92,
    Blade_Spin: 88,
    Blade_Control: 75,
    Blade_Power: 92,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 79,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A direct rival to the ALC class. The Aramid Carbon weave creates a balanced hardness that is optimized for speed-oriented topspin players who want to dominate the first three balls.",
  },
  {
    Blade_Name: "Tibhar Shang Kun Hybrid ZC",
    Blade_Brand: "Tibhar",
    Blade_Speed: 94,
    Blade_Spin: 90,
    Blade_Control: 77,
    Blade_Power: 94,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 72,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The inner Zylon-Carbon construction offers a unique \"hold-and-release\" feel. It is one of the most powerful inner-fiber blades on the market, perfect for massive mid-distance looping.",
  },
  {
    Blade_Name: "Victas Swat Power",
    Blade_Brand: "Victas",
    Blade_Speed: 88,
    Blade_Spin: 94,
    Blade_Control: 81,
    Blade_Power: 88,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 76,
    Blade_Material: "All-Wood",
    Blade_Description: "One of the most popular 7-ply blades in Japan. It is stiffer than a Clipper but maintains a \"soft\" impact feel, making it incredible for the high-tension rubber era.",
  },
  {
    Blade_Name: "Stiga Inspira Hybrid Carbon",
    Blade_Brand: "Stiga",
    Blade_Speed: 95,
    Blade_Spin: 87,
    Blade_Control: 74,
    Blade_Power: 95,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 86,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Stiga\u2019s modern speed king. The hybrid carbon provides a wider sweet spot than traditional ALC, making it extremely reliable during high-speed, off-center exchanges.",
  },
  {
    Blade_Name: "Andro Kanter FO",
    Blade_Brand: "Andro",
    Blade_Speed: 90,
    Blade_Spin: 95,
    Blade_Control: 82,
    Blade_Power: 90,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "A 6mm Balsa core creates a \"weightless\" feel. It offers massive speed in the \"top gear\" but remains surprisingly easy to control during short-game pushes and blocks.",
  },
  {
    Blade_Name: "Gewo In-Force ARC Off-",
    Blade_Brand: "Gewo",
    Blade_Speed: 87,
    Blade_Spin: 98,
    Blade_Control: 85,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 62,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The tamer brother of the Force ARC. The inner placement provides a flexible feel that is ideal for spin-oriented attackers who use hybrid or sticky rubbers.",
  },
  {
    Blade_Name: "Yasaka Ma Lin Soft Carbon",
    Blade_Brand: "Yasaka",
    Blade_Speed: 82,
    Blade_Spin: 99,
    Blade_Control: 88,
    Blade_Power: 82,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 55,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The benchmark for \"control carbon.\" It adds just enough stability to a 5-ply wood to increase the sweet spot without sacrificing the legendary Ma Lin \"touch.\"",
  },
  {
    Blade_Name: "Tibhar Bernadette Szocs Signature",
    Blade_Brand: "Tibhar",
    Blade_Speed: 85,
    Blade_Spin: 97,
    Blade_Control: 84,
    Blade_Power: 85,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "All-Wood",
    Blade_Description: "A high-feeling 7-ply wood. It is designed for consistency and placement, offering a solid \"thud\" on contact that builds confidence in high-pressure rallies.",
  },
  {
    Blade_Name: "Victas ZX-Gear Out",
    Blade_Brand: "Victas",
    Blade_Speed: 94,
    Blade_Spin: 87,
    Blade_Control: 74,
    Blade_Power: 94,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 83,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Utilizing Zexion fiber, this blade offers a unique elasticity. It feels less \"dead\" than traditional carbon blades, providing more energy return on mid-power loops.",
  },
  {
    Blade_Name: "Donic Waldner Senso Carbon",
    Blade_Brand: "Donic",
    Blade_Speed: 84,
    Blade_Spin: 99,
    Blade_Control: 89,
    Blade_Power: 84,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 58,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The \"Maestro's\" choice. The inner carbon plies combined with the Senso handle offer the most sensitive ball feedback in the carbon category.",
  },
  {
    Blade_Name: "Andro Ligna F.R. OFF",
    Blade_Brand: "Andro",
    Blade_Speed: 79,
    Blade_Spin: 99,
    Blade_Control: 92,
    Blade_Power: 79,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "All-Wood",
    Blade_Description: "Cold-pressed wood manufacturing. This blade offers a distinct \"acoustic\" resonance that technical players use to gauge the exact spin on the ball.",
  },
  {
    Blade_Name: "Gewo Sensus Carbo Speed",
    Blade_Brand: "Gewo",
    Blade_Speed: 96,
    Blade_Spin: 81,
    Blade_Control: 68,
    Blade_Power: 96,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 92,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "An uncompromising speed machine. Hard wood veneers over a stiff carbon layer prioritize flat hitting and aggressive \"kill\" shots.",
  },
  {
    Blade_Name: "Yasaka Falck Carbon",
    Blade_Brand: "Yasaka",
    Blade_Speed: 93,
    Blade_Spin: 89,
    Blade_Control: 76,
    Blade_Power: 93,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 80,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "Developed for Mattias Falck. It provides the stability needed for short-pips attacking while offering enough flex for his heavy topspin forehand.",
  },
  {
    Blade_Name: "Tibhar Fortino Pro",
    Blade_Brand: "Tibhar",
    Blade_Speed: 95,
    Blade_Spin: 86,
    Blade_Control: 73,
    Blade_Power: 95,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 75,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "Utilizing Dyneema (the world\u2019s strongest fiber), this blade offers a unique \"vibration-free\" power that feels incredibly stable during high-speed exchanges.",
  },
  {
    Blade_Name: "Victas Liam Pitchford",
    Blade_Brand: "Victas",
    Blade_Speed: 95,
    Blade_Spin: 84,
    Blade_Control: 71,
    Blade_Power: 95,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 87,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A power-hitting tool. It is optimized for the modern, high-intensity backhand flick and aggressive counter-looping style favored by Pitchford.",
  },
  {
    Blade_Name: "Donic Burn OFF",
    Blade_Brand: "Donic",
    Blade_Speed: 87,
    Blade_Spin: 93,
    Blade_Control: 80,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 78,
    Blade_Material: "All-Wood",
    Blade_Description: "The wood is \"burned\" at high temperatures to remove moisture and increase stiffness. This creates a fast, lightweight, all-wood blade with a unique crisp sound.",
  },
  {
    Blade_Name: "Andro Gauzy SL OFF",
    Blade_Brand: "Andro",
    Blade_Speed: 90,
    Blade_Spin: 90,
    Blade_Control: 77,
    Blade_Power: 90,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 88,
    Blade_Material: "All-Wood",
    Blade_Description: "The Ebony outer plies make this one of the hardest all-wood blades available. It is designed for direct, linear power without the \"artificial\" feel of carbon.",
  },
  {
    Blade_Name: "Gewo Zoom Pro",
    Blade_Brand: "Gewo",
    Blade_Speed: 76,
    Blade_Spin: 99,
    Blade_Control: 93,
    Blade_Power: 76,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 55,
    Blade_Material: "All-Wood",
    Blade_Description: "The classic \"learning\" blade. It provides the perfect feedback loop for developing players to master their stroke mechanics before moving to carbon.",
  },
  {
    Blade_Name: "Stiga Cybershape Carbon",
    Blade_Brand: "Stiga",
    Blade_Speed: 93,
    Blade_Spin: 91,
    Blade_Control: 78,
    Blade_Power: 93,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 72,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The hexagonal shape isn't just a gimmick\u2014it increases the sweet spot in the hitting area. The inner carbon provides a massive \"hold\" for high-arc loops.",
  },
  {
    Blade_Name: "Yasaka Alnade",
    Blade_Brand: "Yasaka",
    Blade_Speed: 91,
    Blade_Spin: 90,
    Blade_Control: 77,
    Blade_Power: 91,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 77,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A hidden gem. It uses PA Carbon (similar to ALC) but with a slightly softer touch, making it a very accessible \"pro-level\" offensive blade.",
  },
  {
    Blade_Name: "Tibhar Samsonov Force Pro",
    Blade_Brand: "Tibhar",
    Blade_Speed: 87,
    Blade_Spin: 95,
    Blade_Control: 82,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 74,
    Blade_Material: "All-Wood",
    Blade_Description: "Vladimir Samsonov\u2019s choice for years. It is a slightly faster version of the Clipper, offering a solid and dependable feel for allround-offensive players.",
  },
  {
    Blade_Name: "Victas Dyna Five",
    Blade_Brand: "Victas",
    Blade_Speed: 74,
    Blade_Spin: 99,
    Blade_Control: 95,
    Blade_Power: 74,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 50,
    Blade_Material: "All-Wood",
    Blade_Description: "Pure control. This blade is designed for players who win through variation and placement rather than speed. Perfect for technical \"touch\" players.",
  },
  {
    Blade_Name: "Donic Crest OFF",
    Blade_Brand: "Donic",
    Blade_Speed: 94,
    Blade_Spin: 88,
    Blade_Control: 75,
    Blade_Power: 94,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 85,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A complex 9-ply construction. The thin veneers provide a \"luxury\" feeling with a huge sweet spot and linear power delivery.",
  },
  {
    Blade_Name: "Andro TP Ligna ALL",
    Blade_Brand: "Andro",
    Blade_Speed: 70,
    Blade_Spin: 99,
    Blade_Control: 98,
    Blade_Power: 70,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 45,
    Blade_Material: "All-Wood",
    Blade_Description: "The ultimate precision tool. Each blade is weighed and tested to ensure the highest level of ball-feeling and control for tactical allrounders.",
  },
  {
    Blade_Name: "Andro Timber 7 OFF",
    Blade_Brand: "Andro",
    Blade_Speed: 85,
    Blade_Spin: 96,
    Blade_Control: 83,
    Blade_Power: 85,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 74,
    Blade_Material: "All-Wood",
    Blade_Description: "The pure-wood alternative to carbon. It offers a solid, vibration-free contact that is perfect for players transitioning from beginner setups to competitive league play.",
  },
  {
    Blade_Name: "Gewo Balsa Carbon 575",
    Blade_Brand: "Gewo",
    Blade_Speed: 89,
    Blade_Spin: 97,
    Blade_Control: 84,
    Blade_Power: 89,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 68,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "A masterpiece of weight-to-power ratio. The 5.75mm balsa core makes it incredibly light, while the carbon layers ensure the stability needed for modern offensive topspin.",
  },
  {
    Blade_Name: "Yasaka Ma Lin Extra Off",
    Blade_Brand: "Yasaka",
    Blade_Speed: 83,
    Blade_Spin: 99,
    Blade_Control: 87,
    Blade_Power: 83,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 72,
    Blade_Material: "All-Wood",
    Blade_Description: "One of the most successful blades in history. The hard walnut outer plies provide a crisp \"crack\" on impact, making it the king of mid-distance looping and blocking.",
  },
  {
    Blade_Name: "Donic Waldner Exclusive",
    Blade_Brand: "Donic",
    Blade_Speed: 72,
    Blade_Spin: 99,
    Blade_Control: 95,
    Blade_Power: 72,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 48,
    Blade_Material: "All-Wood",
    Blade_Description: "The ultimate development tool. Designed for precision over power, it forces the player to develop correct technique while providing massive safety on every stroke.",
  },
  {
    Blade_Name: "Victas Swat",
    Blade_Brand: "Victas",
    Blade_Speed: 84,
    Blade_Spin: 99,
    Blade_Control: 86,
    Blade_Power: 84,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "All-Wood",
    Blade_Description: "Japan\u2019s best-selling 7-ply wood. It has a \"soft\" 7-ply feel that provides a massive sweet spot and incredible consistency for the controlled-offensive player.",
  },
  {
    Blade_Name: "Tibhar Samsonov Alpha",
    Blade_Brand: "Tibhar",
    Blade_Speed: 78,
    Blade_Spin: 99,
    Blade_Control: 91,
    Blade_Power: 78,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 55,
    Blade_Material: "All-Wood",
    Blade_Description: "A slightly smaller head shape makes this blade incredibly maneuverable. It is a legendary \"touch\" blade for players who win with placement and heavy spin.",
  },
  {
    Blade_Name: "Stiga Allround Classic C",
    Blade_Brand: "Stiga",
    Blade_Speed: 79,
    Blade_Spin: 99,
    Blade_Control: 92,
    Blade_Power: 79,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "The modern update to the world\u2019s most famous blade. The carbon adds just enough stability for the poly-ball without losing the legendary Stiga \"feeling.\"",
  },
  {
    Blade_Name: "Andro Inizio",
    Blade_Brand: "Andro",
    Blade_Speed: 70,
    Blade_Spin: 99,
    Blade_Control: 97,
    Blade_Power: 70,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 45,
    Blade_Material: "All-Wood",
    Blade_Description: "A high-quality entry-level competitive blade. It offers the linear feedback necessary for learning how to read incoming spin and execute controlled counters.",
  },
  {
    Blade_Name: "Joola Rossi Allround",
    Blade_Brand: "Joola",
    Blade_Speed: 74,
    Blade_Spin: 99,
    Blade_Control: 94,
    Blade_Power: 74,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 50,
    Blade_Material: "All-Wood",
    Blade_Description: "Named after the legend Mr. Rossi. This blade is optimized for a balanced game, offering a \"safety first\" approach for tactical players.",
  },
  {
    Blade_Name: "Gewo Zoom Pro Off-",
    Blade_Brand: "Gewo",
    Blade_Speed: 81,
    Blade_Spin: 99,
    Blade_Control: 88,
    Blade_Power: 81,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 62,
    Blade_Material: "All-Wood",
    Blade_Description: "Often called the \"Korbel Killer.\" It offers a very similar feel to high-end Butterfly wood blades but with a slightly more modern, crisp finish.",
  },
  {
    Blade_Name: "Yasaka Sweden Extra",
    Blade_Brand: "Yasaka",
    Blade_Speed: 75,
    Blade_Spin: 99,
    Blade_Control: 96,
    Blade_Power: 75,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 52,
    Blade_Material: "All-Wood",
    Blade_Description: "Produced in the famous factory in Huskvarna. This blade is the gold standard for \"feeling,\" used by pros and amateurs alike to master the short game.",
  },
  {
    Blade_Name: "Donic Persson Powerplay",
    Blade_Brand: "Donic",
    Blade_Speed: 87,
    Blade_Spin: 93,
    Blade_Control: 80,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 78,
    Blade_Material: "All-Wood",
    Blade_Description: "A unique construction using two thin dampening foils. This gives it 7-ply speed with a 5-ply feel, perfect for aggressive driving and smashing.",
  },
  {
    Blade_Name: "Tibhar Stratus Power Wood",
    Blade_Brand: "Tibhar",
    Blade_Speed: 84,
    Blade_Spin: 98,
    Blade_Control: 85,
    Blade_Power: 84,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 65,
    Blade_Material: "All-Wood",
    Blade_Description: "A modern offensive wood blade that mimics the feel of the Korbel but with a slightly larger sweet spot and more \"kick\" for mid-distance play.",
  },
  {
    Blade_Name: "Sanwei Target 7",
    Blade_Brand: "Sanwei",
    Blade_Speed: 91,
    Blade_Spin: 89,
    Blade_Control: 76,
    Blade_Power: 91,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 82,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "The best \"budget Viscaria\" clone. For under $50, you get a high-quality Koto-ALC construction that provides professional-grade speed and stiffness.",
  },
  {
    Blade_Name: "Palio TCT",
    Blade_Brand: "Palio",
    Blade_Speed: 95,
    Blade_Spin: 83,
    Blade_Control: 70,
    Blade_Power: 95,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 90,
    Blade_Material: "Outer-Carbon",
    Blade_Description: "A technical anomaly. The titanium/carbon weave creates an incredibly stiff surface that is perfect for long-pips players or flat-hitting attackers.",
  },
  {
    Blade_Name: "Xiom Offensive S",
    Blade_Brand: "Xiom",
    Blade_Speed: 82,
    Blade_Spin: 98,
    Blade_Control: 86,
    Blade_Power: 82,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 64,
    Blade_Material: "All-Wood",
    Blade_Description: "A classic offensive blade with a refined finish. It offers a very linear speed progression, making it a predictable and reliable partner for topspin rallies.",
  },
  {
    Blade_Name: "Andro Timber 5 ALL/S",
    Blade_Brand: "Andro",
    Blade_Speed: 75,
    Blade_Spin: 99,
    Blade_Control: 94,
    Blade_Power: 75,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 58,
    Blade_Material: "All-Wood",
    Blade_Description: "The Koto outer ply gives this allround blade a \"pro\" feel. It\u2019s perfect for the technical player who wants carbon-like precision in an all-wood build.",
  },
  {
    Blade_Name: "Gewo Neofaxx Off",
    Blade_Brand: "Gewo",
    Blade_Speed: 84,
    Blade_Spin: 95,
    Blade_Control: 82,
    Blade_Power: 84,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 66,
    Blade_Material: "All-Wood",
    Blade_Description: "Specifically designed for the \"Neofaxx\" rubber series. It\u2019s a balanced offensive blade that excels at high-arc looping and safe opening attacks.",
  },
  {
    Blade_Name: "Donic Appelgren Allplay",
    Blade_Brand: "Donic",
    Blade_Speed: 68,
    Blade_Spin: 99,
    Blade_Control: 98,
    Blade_Power: 68,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 40,
    Blade_Material: "All-Wood",
    Blade_Description: "The ultimate \"control\" blade. If you can't control the ball with this, it\u2019s not the equipment\u2019s fault. It is a defensive and tactical masterpiece.",
  },
  {
    Blade_Name: "Victas Award Offensive",
    Blade_Brand: "Victas",
    Blade_Speed: 81,
    Blade_Spin: 99,
    Blade_Control: 87,
    Blade_Power: 81,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "All-Wood",
    Blade_Description: "A high-quality Japanese-designed blade that focuses on \"easy-to-play\" metrics. It has a soft touch that makes blocking feel effortless.",
  },
  {
    Blade_Name: "Yasaka Silver All Wood",
    Blade_Brand: "Yasaka",
    Blade_Speed: 79,
    Blade_Spin: 99,
    Blade_Control: 91,
    Blade_Power: 79,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 70,
    Blade_Material: "All-Wood",
    Blade_Description: "The outer plies are specially treated to be harder than standard wood, providing a \"high-tech\" all-wood feel for a modern, spin-based game.",
  },
  {
    Blade_Name: "DHS Power G3",
    Blade_Brand: "DHS",
    Blade_Speed: 83,
    Blade_Spin: 98,
    Blade_Control: 85,
    Blade_Power: 83,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 62,
    Blade_Material: "All-Wood",
    Blade_Description: "The 5-ply version of the Power G series. It offers a huge amount of \"flex,\" which translates to massive spin production on slow loops.",
  },
  {
    Blade_Name: "Friendship 729 Z-1",
    Blade_Brand: "Friendship",
    Blade_Speed: 82,
    Blade_Spin: 98,
    Blade_Control: 86,
    Blade_Power: 82,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "All-Wood",
    Blade_Description: "An incredible budget find. It is often compared to the Stiga Offensive Classic but with a slightly thicker core for better stability in the poly-ball era.",
  },
  {
    Blade_Name: "Yinhe (Galaxy) T-11+",
    Blade_Brand: "Yinhe",
    Blade_Speed: 94,
    Blade_Spin: 85,
    Blade_Control: 72,
    Blade_Power: 94,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 150,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 85,
    Blade_Material: "Inner-Carbon",
    Blade_Description: "One of the fastest budget blades in existence. At around 70g, it is a lightning-fast weapon for players who want maximum speed without the weight.",
  },
  {
    Blade_Name: "Tibhar Drinkhall Allround",
    Blade_Brand: "Tibhar",
    Blade_Speed: 74,
    Blade_Spin: 99,
    Blade_Control: 94,
    Blade_Power: 74,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 52,
    Blade_Material: "All-Wood",
    Blade_Description: "Designed by Paul Drinkhall. This blade focuses on the \"all-around offensive\" style\u2014winning through placement, variations, and consistent pressure.",
  },
  {
    Blade_Name: "Andro Gauzy ALL",
    Blade_Brand: "Andro",
    Blade_Speed: 72,
    Blade_Spin: 99,
    Blade_Control: 96,
    Blade_Power: 72,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Beginner",
    Blade_Style: "Allround",
    Blade_Weight: 85,
    Blade_Stiffness: 50,
    Blade_Material: "All-Wood",
    Blade_Description: "Simon Gauzy\u2019s \"entry\" signature blade. It emphasizes the \"art\" of table tennis\u2014touch, spin, and ball-feeling\u2014making it a joy to play with.",
  },
  {
    Blade_Name: "Gewo Play Off",
    Blade_Brand: "Gewo",
    Blade_Speed: 80,
    Blade_Spin: 98,
    Blade_Control: 86,
    Blade_Power: 80,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 60,
    Blade_Material: "All-Wood",
    Blade_Description: "A no-nonsense offensive blade. It is built to be a reliable \"workhorse\" for club players who need a balanced tool for all aspects of the game.",
  },
  {
    Blade_Name: "Stiga Azalea Allround",
    Blade_Brand: "Stiga",
    Blade_Speed: 76,
    Blade_Spin: 99,
    Blade_Control: 93,
    Blade_Power: 76,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 55,
    Blade_Material: "All-Wood",
    Blade_Description: "Inspired by the Japanese culture, this blade offers a \"soft\" feel and a beautiful finish. It is slightly faster than the Allround Classic, fitting the modern game better.",
  },
  {
    Blade_Name: "Donic Burn All+",
    Blade_Brand: "Donic",
    Blade_Speed: 78,
    Blade_Spin: 99,
    Blade_Control: 92,
    Blade_Power: 78,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Intermediate",
    Blade_Style: "All-Round",
    Blade_Weight: 85,
    Blade_Stiffness: 65,
    Blade_Material: "All-Wood",
    Blade_Description: "The thermally treated wood gives it a \"seasoned\" feel, providing a consistent bounce and a crisp sound that is rare at this price point.",
  },
  {
    Blade_Name: "Sanwei Fextra 7",
    Blade_Brand: "Sanwei",
    Blade_Speed: 87,
    Blade_Spin: 94,
    Blade_Control: 81,
    Blade_Power: 87,
    Blade_Grip: ["FL", "ST"],
    Blade_Price: 80,
    Blade_Level: "Advanced",
    Blade_Style: "Offensive",
    Blade_Weight: 85,
    Blade_Stiffness: 76,
    Blade_Material: "All-Wood",
    Blade_Description: "Widely regarded as the best budget 7-ply wood on the market. It mimics the Stiga Clipper\u2019s power profile but with a slightly more modern, flexible feel.",
  },
];
