import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";

const Terms = () => {
  const currentYear = new Date().getFullYear();

  return (
    <div className="flex min-h-screen flex-col">
      <SEO
        title="Terms & Disclaimer"
        description="Read TopPaddle's terms of service and disclaimer. Important information about quiz results and product recommendations."
        canonical="https://dcabed67-45bf-49e1-a6f1-a63e629bf863.lovableproject.com/terms"
        noindex={true}
      />
      <Header />
      <main className="flex-1 bg-background">
        <div className="container mx-auto px-4 py-16 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-4xl">
            <h1 className="font-headline text-4xl font-bold text-foreground">
              Terms of Service – TopTableTennisPaddle.com
            </h1>
            <p className="font-body mt-4 text-sm text-muted-foreground">
              Last Updated: October 2025
            </p>

            {/* Order and Purchase Terms */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Order and Purchase Terms
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                By placing an order through TopTableTennisPaddle.com, you agree to purchase the products at the prices displayed at checkout.
                All orders are subject to acceptance and availability. We reserve the right to refuse or cancel any order for any reason.
              </p>
            </section>

            {/* Payment Terms */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Payment Terms
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                All payments are processed securely through our payment provider.
                We accept major credit cards and other payment methods as displayed at checkout.
                Prices are in USD unless otherwise stated. You agree to pay all charges at the prices in effect when you place your order.
              </p>
            </section>

            {/* Shipping and Delivery */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Shipping and Delivery
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Shipping times and costs vary by location and product availability.
                Estimated delivery times are provided at checkout but are not guaranteed.
                Risk of loss and title for products pass to you upon delivery to the carrier.
              </p>
            </section>

            {/* Returns and Refunds */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Returns and Refunds
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                We accept returns within 30 days of delivery for unused products in original packaging.
                Custom-assembled rackets may have different return policies.
                Refunds will be processed to the original payment method within 7-10 business days after we receive the returned item.
                Shipping costs are non-refundable unless the return is due to our error.
              </p>
            </section>

            {/* Product Warranties */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Product Warranties
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Products are covered by manufacturer warranties where applicable.
                We are not responsible for manufacturer defects beyond facilitating warranty claims.
                Custom assembly services are guaranteed for workmanship quality.
              </p>
            </section>

            {/* Quiz Results Disclaimer */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Quiz Results Disclaimer
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Equipment recommendations generated by our quiz are guidelines only.
                Results vary by player, style, and skill level.
                We encourage testing equipment and consulting experienced players before purchasing.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Limitation of Liability
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                TopTableTennisPaddle.com provides products and content "as is".
                To the maximum extent permitted by law, we are not liable for:
              </p>
              <ul className="font-body mt-4 list-inside list-disc space-y-2 text-muted-foreground">
                <li>Injuries or dissatisfaction resulting from product use</li>
                <li>Delays in shipping or delivery</li>
                <li>Product performance or suitability for specific purposes</li>
                <li>Loss of profits or indirect damages</li>
              </ul>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Our total liability for any claim shall not exceed the amount you paid for the product.
              </p>
            </section>

            {/* Product Information Accuracy */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Product Information Accuracy
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                We strive to keep product specifications, descriptions, and prices accurate.
                However, errors may occur. If a product is listed at an incorrect price or with incorrect information,
                we reserve the right to refuse or cancel orders for that product.
              </p>
            </section>

            {/* Intellectual Property */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Intellectual Property & Code Ownership
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                All content, including text, graphics, images, algorithms, and code, is the intellectual property of TopTableTennisPaddle.com.
              </p>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Some portions of code/algorithm were developed with AI tools (e.g., Lovable).
                All custom logic and configuration belong exclusively to TopTableTennisPaddle.com.
              </p>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                You may not copy, reproduce, distribute, or modify any part of this site without written permission.
              </p>
            </section>

            {/* Changes to Terms */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Changes to Terms
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                We may update these terms at any time.
                Continued use constitutes acceptance of updated Terms.
              </p>
            </section>

            {/* Contact */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Contact
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Questions? Contact us via{" "}
                <a href="mailto:toppaddlewebsite@gmail.com" className="text-primary hover:underline">
                  toppaddlewebsite@gmail.com
                </a>
              </p>
            </section>

            {/* Copyright */}
            <section className="mt-12 border-t border-border pt-8">
              <p className="font-body text-center text-sm text-muted-foreground">
                © {currentYear} TopTableTennisPaddle.com – All rights reserved. Unauthorized copying is prohibited.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
