import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";

const Terms = () => {
  const currentYear = new Date().getFullYear();

  return (
    <div className="flex min-h-screen flex-col">
      <SEO
        title="Terms & Disclaimer"
        description="Read TopPaddle's terms of service and disclaimer. Important information about quiz results and product recommendations."
        canonical="https://dcabed67-45bf-49e1-a6f1-a63e629bf863.lovableproject.com/terms"
        noindex={true}
      />
      <Header />
      <main className="flex-1 bg-background">
        <div className="container mx-auto px-4 py-16 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-4xl">
            <h1 className="font-headline text-4xl font-bold text-foreground">
              Terms & Disclaimer – TopTableTennisPaddle.com
            </h1>
            <p className="font-body mt-4 text-sm text-muted-foreground">
              Last Updated: October 2025
            </p>

            {/* Quiz Results Disclaimer */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Quiz Results Disclaimer
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Recommendations generated by our quiz are guidelines only.
                Results vary by player, style, and skill level.
                We encourage testing equipment and consulting experienced players before purchasing.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Limitation of Liability
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                TopTableTennisPaddle.com provides content "as is".
                We are not responsible for:
              </p>
              <ul className="font-body mt-4 list-inside list-disc space-y-2 text-muted-foreground">
                <li>Product quality, pricing, or availability</li>
                <li>Shipping/returns/customer service of retailers</li>
                <li>Injuries or dissatisfaction from equipment</li>
                <li>Errors in product information</li>
              </ul>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Use the website at your own risk.
              </p>
            </section>

            {/* Use of Service */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Use of Service
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                By using TopTableTennisPaddle.com:
              </p>
              <ul className="font-body mt-4 list-inside list-disc space-y-2 text-muted-foreground">
                <li>You acknowledge recommendations are advisory only</li>
                <li>You accept full responsibility for purchases</li>
              </ul>
            </section>

            {/* Product Information Accuracy */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Product Information Accuracy
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                We strive to keep specifications and prices accurate, but always verify on retailer websites.
                Displayed prices are estimates only.
              </p>
            </section>

            {/* Intellectual Property */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Intellectual Property & Code Ownership
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                All content, including text, graphics, images, algorithms, and code, is the intellectual property of TopTableTennisPaddle.com.
              </p>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Some portions of code/algorithm were developed with AI tools (e.g., Lovable).
                All custom logic and configuration belong exclusively to TopTableTennisPaddle.com.
              </p>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                You may not copy, reproduce, distribute, or modify any part of this site without written permission.
              </p>
            </section>

            {/* Changes to Terms */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Changes to Terms
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                We may update these terms at any time.
                Continued use constitutes acceptance of updated Terms.
              </p>
            </section>

            {/* Contact */}
            <section className="mt-12">
              <h2 className="font-headline text-2xl font-semibold text-foreground">
                Contact
              </h2>
              <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                Questions? Contact us via{" "}
                <a href="mailto:toppaddlewebsite@gmail.com" className="text-primary hover:underline">
                  toppaddlewebsite@gmail.com
                </a>
              </p>
            </section>

            {/* Copyright */}
            <section className="mt-12 border-t border-border pt-8">
              <p className="font-body text-center text-sm text-muted-foreground">
                © {currentYear} TopTableTennisPaddle.com – All rights reserved. Unauthorized copying is prohibited.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
