import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service – TopTableTennisPaddle.com",
    description: "Read the terms of service for TopTableTennisPaddle.com, a table tennis equipment recommendation and lead generation platform.",
    robots: {
        index: false,
        follow: true,
    },
};

export default function Terms() {
    const currentYear = new Date().getFullYear();

    return (
        <div className="min-h-screen flex flex-col bg-gradient-to-br from-background via-background to-primary/5">
            <Header />
            <main className="flex-1">
                <div className="container mx-auto px-4 py-16 sm:px-6 lg:px-8">
                    <div className="mx-auto max-w-4xl">
                        <h1 className="font-headline text-4xl font-bold text-foreground">
                            Terms of Service – TopTableTennisPaddle.com
                        </h1>
                        <p className="font-body mt-4 text-sm text-muted-foreground">
                            Last Updated: March 2026
                        </p>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">1. About This Platform</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                TopTableTennisPaddle.com is an informational and lead generation platform. We provide free tools — including a smart quiz, a product configurator, and a comparator — to help players find the right table tennis equipment.
                            </p>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                We do not sell products directly. When you submit a quote request, your details are shared with certified table tennis retailers who will contact you with personalized pricing offers.
                            </p>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">2. Use of the Site</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                By using this site, you agree to use it only for lawful, personal purposes. You must not:
                            </p>
                            <ul className="font-body mt-4 list-inside list-disc space-y-2 text-muted-foreground">
                                <li>Submit false or misleading information in quote request forms.</li>
                                <li>Scrape, copy, or reproduce any content without written permission.</li>
                                <li>Attempt to reverse-engineer or interfere with our recommendation algorithms.</li>
                            </ul>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">3. Lead Generation & Retailer Contact</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                When you click "Ask for an offer from the best shops" and submit the form, you consent to having your name, email address, and equipment preferences shared with one or more certified table tennis retailers. These retailers may contact you by email with pricing quotes for the equipment you selected.
                            </p>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                We act as a lead generation intermediary. We are not responsible for the pricing, availability, quality, or customer service provided by the retailers who contact you. Any transaction you make with a retailer is solely between you and that retailer.
                            </p>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">4. Recommendation Disclaimer</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                Equipment recommendations generated by our quiz and configurator tools are guidelines only. Results vary by player skill level, playing style, and personal preference. We encourage you to test equipment and consult experienced players before purchasing.
                            </p>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                We are not responsible for any dissatisfaction with equipment purchased based on our recommendations.
                            </p>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">5. Limitation of Liability</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                TopTableTennisPaddle.com provides its tools and content "as is." To the maximum extent permitted by law, we are not liable for:
                            </p>
                            <ul className="font-body mt-4 list-inside list-disc space-y-2 text-muted-foreground">
                                <li>Dissatisfaction with equipment purchased through a retailer referral.</li>
                                <li>Inaccuracies in product specifications or pricing provided by third-party retailers.</li>
                                <li>Any indirect, incidental, or consequential damages arising from use of this site.</li>
                            </ul>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">6. Intellectual Property</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                All content on this site — including text, graphics, images, algorithms, quiz logic, and recommendation code — is the intellectual property of TopTableTennisPaddle.com. You may not copy, reproduce, distribute, or modify any part of this site without written permission.
                            </p>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">7. Changes to Terms</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                We may update these terms at any time. Continued use of the site constitutes acceptance of the updated terms.
                            </p>
                        </section>

                        <section className="mt-12">
                            <h2 className="font-headline text-2xl font-semibold text-foreground">8. Contact Us</h2>
                            <p className="font-body mt-4 leading-relaxed text-muted-foreground">
                                For questions about these terms, contact us at{" "}
                                <a href="mailto:toppaddlewebsite@gmail.com" className="text-primary hover:underline">
                                    toppaddlewebsite@gmail.com
                                </a>
                                . We aim to reply within 1–2 business days.
                            </p>
                        </section>

                        <section className="mt-12 border-t border-border pt-8">
                            <p className="font-body text-center text-sm text-muted-foreground">
                                © {currentYear} TopTableTennisPaddle.com – All rights reserved. Unauthorized copying is prohibited.
                            </p>
                        </section>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
